### ISSUE TITLE
Create an instance without an API token

### ISSUE THREAD

**Issue by MicroDroid** [discordbots/botlister#5]
Consider the case of that I don't have a bot on that bot list. How can I fetch information for other bots?

**Comment by wr1ght** [comment]
@MicroDroid by not passing an API token to the class

```new Botlister({})```

**Comment by wr1ght** [comment]
https://github.com/discordbots/botlister/blob/709d7e811091b610faa242cbda19b9e1f4128279/src/core/Core.js#L8

**Comment by MicroDroid** [comment]
`new Botlister()` should work though.
